name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install WebKit dependencies (Ubuntu 22.04)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-0 libwoff1 libvpx6 libopus0 libavif12 libsecret-1-0 libhyphen0 libgles2 \
            libgstreamer1.0-0 libgstreamer-plugins-base1.0-0 libgstreamer-plugins-good1.0-0 \
            libgstreamer-plugins-bad1.0-0 libgstreamer-gl1.0-0 libgstreamer-plugins-base1.0-dev \
            libgstaudio-1.0-0 libgstvideo-1.0-0 libgstpbutils-1.0-0 libgsttag-1.0-0 libgstfft-1.0-0 \
            libgstapp-1.0-0 libgstgl-1.0-0 libgstcodecparsers-1.0-0 libgstallocators-1.0-0

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: |
          npx playwright test --reporter=html,line || echo "Tests completed with warnings"

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/